# Generated by Django 3.1.3 on 2020-11-16 10:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_event_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='reserved_until',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
