# Generated by Django 3.1.3 on 2020-11-16 10:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_auto_20201116_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='reserved_until',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 11, 16, 10, 24, 39, 861628, tzinfo=utc)),
        ),
    ]
