# Generated by Django 3.1.3 on 2020-11-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_auto_20201116_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='reserved_until',
            field=models.DateTimeField(),
        ),
    ]
