# Generated by Django 3.1.3 on 2020-11-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_auto_20201116_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='reservation_number',
            field=models.CharField(default='value', max_length=28),
            preserve_default=False,
        ),
    ]
