# Generated by Django 3.1.3 on 2020-11-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_ticket_reservation_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
