# Generated by Django 3.1.3 on 2020-11-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_auto_20201117_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='payment_status',
            field=models.CharField(default='none', max_length=128),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(max_length=128),
        ),
    ]
